version: 2
updates:
  # Enable version updates for npm (backend)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "foodtracker-team"
    assignees:
      - "foodtracker-team"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      # Ignore major version updates for production dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "foodtracker-team"
    assignees:
      - "foodtracker-team"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignore major version updates for production dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm (shared)
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 3
    reviewers:
      - "foodtracker-team"
    assignees:
      - "foodtracker-team"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "shared"

  # Enable version updates for npm (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 3
    reviewers:
      - "foodtracker-team"
    assignees:
      - "foodtracker-team"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "root"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "foodtracker-team"
    assignees:
      - "foodtracker-team"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 3
    reviewers:
      - "foodtracker-team"
    assignees:
      - "foodtracker-team"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "backend"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 3
    reviewers:
      - "foodtracker-team"
    assignees:
      - "foodtracker-team"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"