services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.simple
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_PATH=/app/data/foodtracker.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data:
    driver: local