name: 🐛 Rapport de Bug
description: Signaler un bug ou un dysfonctionnement
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug ! Votre contribution aide à améliorer FoodTracker.

  - type: textarea
    id: description
    attributes:
      label: Description du problème
      description: Décrivez clairement le problème rencontré
      placeholder: |
        Exemple: Lorsque j'essaie d'ajouter un aliment à un repas, l'application plante...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment peut-on reproduire ce bug ?
      placeholder: |
        1. Aller sur la page '...'
        2. Cliquer sur '...'
        3. Faire défiler jusqu'à '...'
        4. Observer l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
      placeholder: L'aliment devrait être ajouté au repas sans erreur.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il réellement ?
      placeholder: L'application plante et affiche une erreur 500.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Composant affecté
      description: Dans quelle partie de l'application le bug se produit-il ?
      options:
        - Frontend (React)
        - Backend (NestJS)
        - Base de données
        - API externe (OpenFoodFacts)
        - MCP Server
        - Docker/Déploiement
        - Documentation
        - Non sûr
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: |
        Informations sur votre environnement:
      value: |
        - OS: [e.g. macOS, Windows, Linux]
        - Navigateur: [e.g. Chrome 120, Firefox 115]
        - Version Node.js: [e.g. 18.17.0]
        - Version de l'app: [e.g. commit hash ou tag]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs et erreurs
      description: Copier/coller les logs d'erreur ou captures d'écran
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Vérifications
      description: Avant de soumettre ce rapport
      options:
        - label: J'ai vérifié qu'il n'y a pas déjà un issue similaire
          required: true
        - label: J'ai testé avec la dernière version du code
          required: true