name: Pre-Build TypeScript Check

on:
  pull_request:
    paths:
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'
      - 'frontend/package.json'
      - 'frontend/tsconfig*.json'
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'
      - 'frontend/package.json'
      - 'frontend/tsconfig*.json'

jobs:
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Run TypeScript check
        run: |
          cd frontend
          npm run typecheck
          
      - name: Run ESLint
        run: |
          cd frontend
          npm run lint
        continue-on-error: true # Don't fail on lint warnings
        
      - name: Comment PR on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ TypeScript check failed! Please run `npm run typecheck` locally to see the errors.'
            })